export const CONTACT_EMAIL = 'paczka94@gmail.com';

export const SKILLS = [
  'TypeScript',
  'JavaScript',
  'Node.js',
  'Express',
  'NestJS',
  'GraphQL',
  'REST',
  'MongoDB',
  'PostgreSQL',
  'Redis',
  'RabbitMQ',
  'Kafka',
  'Elasticsearch',
  'Kibana',
  'Docker',
  'Microservices',
  'API design',
  'Event-driven architecture',
  'Domain-driven design',
  'TDD',
  'CI/CD',
  'Claude Code',
  'ChatGPT',
  'Cursor',
] as const;

export const INTEGRATIONS = [
  'Shopify',
  'BitLabs',
  'Rithum',
  'Stripe',
  'PayPal',
  'Klarna',
  'FedEx',
  'UPS',
  'Canada Post',
] as const;
